.\" This file is distributed under the same license as the qterm
.\" package.
.\" Copyright (C) LI Daobing <lidaobing@gmail.com>, 2008.
.\"
.TH "QTERM" 1 "September 14, 2005" "" ""
.SH NAME
qterm \- BBS client for X Window System written in Qt

.SH "SYNOPSIS"
.B qterm

.SH "DESCRIPTION"

.PP
This manual page documents briefly the \fBqterm\fR command.

.PP
This manual page was written for the Debian distribution because the
original program does not have a manual page.

.PP
QTerm is a BBS client for X Window System. It support telnet and ssh1
protocols. It also support zmodem, URL detect, mouse action.

.PP
It also support detecting location from ip address, but you need do some
extra work. (See README.Debian)

.PP
Homepage: http://qterm.sourceforge.net/

.SH "SEE ALSO"
.BR telnet (1),
.BR ssh (1)
